version: '3'

services:
  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: webserver
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    ports:
      - 80:80
    networks:
      - frontend

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html   
    environment:
       WORDPRESS_DB_HOST: database
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
       WORDPRESS_DB_NAME: wordpress
    secrets:
      - db_password
    networks:
      - frontend
      - dbnet

  database:
    image: mysql:latest
    container_name: database
    volumes:
      - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_root_password
       - db_password
    networks:
      - dbnet
    
secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
  wordpress:
  db_data:

networks:
  frontend:
    driver: bridge
  dbnet:
    driver: bridge